server:
  applicationConnectors:
  - type: http
    port: 8061
#    bindHost: 127.0.0.1
  adminConnectors:
  - type: http
    port: 8060
#    bindHost: 127.0.0.1

logging:
  level: INFO
  appenders:
  - type: console
    threshold: ALL
    timeZone: Europe/Berlin
    target: stdout
    logFormat: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

elasticsearch:
  host: 192.168.178.30
#  host: localhost
  port: 9300
  cluster: ecep

# The geocoder adds coordinates to the company addresses based on the postal code.
# The needed source file can be downloaded from: http://www.doogal.co.uk/files/postcodes.zip (~60MB).
geocoder:
  source: postcodes.zip